version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: archguard-architecture-poc-mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: architecture
      MYSQL_ROOT_PASSWORD: root
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --lower_case_table_names=1
